
import turtle

def turtleLetter(letter,tur):
    if letter=="box":
        tur.setheading(0)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)

    elif letter == "A":
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        #fixes
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(35)
        #tur.right(180)
  #tur.right(180)
    elif letter == "B":
    
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        #fixes
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(35)
        #tur.right(180) 
    elif letter == "C":
        tur.setheading(0)
        tur.pd()
        tur.fd(10)
        tur.right(90)
        tur.fd(15)
        tur.right(90)
        tur.fd(10)
    elif letter == "D":
        tur.setheading(0)
        tur.pd()
        tur.fd(30)
        tur.right(90)
        tur.fd(25)
        tur.right(90)
        tur.fd(25)
        tur.right(90)
        tur.fd(25)
    #tur.right(180)
    elif letter == "E":
        tur.setheading(0)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(15)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(30)
    #tur.right(180)
        
    
    elif letter == "F":
        tur.setheading(0)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(15)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        #tur.right(180)


       
    elif letter == "G":
        tur.setheading(0)
        tur.pd()
        tur.right(180)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.pd()
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(15)

        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(20) 
    #tur.right(180)


    elif letter == "H":
        tur.setheading(0)
        tur.pd()
        tur.right(90)
        tur.fd(30)
        tur.left(180)
        tur.fd(15)
        tur.pd()
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(15)
        tur.left(180)
        tur.fd(30)
        #tur.right(180)
    elif letter == "I":
        tur.setheading(0)
        tur.pd()
        tur.right(90)
        tur.fd(30)
        #tur.right(180)
    elif letter == "J":
        tur.setheading(0)
        tur.pd()
        tur.right(180)
        tur.fd(30)
        tur.left(180)
        tur.fd(15)
        tur.pd()
        tur.right(90)
        tur.fd(60)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(10)
        #tur.right(180)
    elif letter == "K":
        tur.setheading(0)
        tur.pd()
        tur.right(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(15)
        tur.right(45)
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.right(270)
        tur.fd(20)
    elif letter == "L":
        tur.setheading(0)
        tur.pd()
        tur.right(90)
        tur.fd(50)
        tur.left(90)
        tur.fd (50)
    elif letter == "M":
        tur.setheading(0)
        tur.pd()
        tur.right(90)
        tur.fd(50)
        tur.left(180)
        tur.fd(50)
        tur.right(135)
        tur.fd(70)
        tur.left(135)
        tur.fd(50)
        tur.right(135)
        tur.fd(70)
    elif letter == "N":
        tur.setheading(0)
        tur.pd()
        tur.right(90)
        tur.fd(50)
        tur.left(180)
        tur.fd(50)
        tur.right(135)
        tur.fd(70)
        tur.left(135)
        tur.fd(50)
    elif letter == "O":
        tur.setheading(0)
        tur.pd()
        tur.fd(50)
        tur.right(90)
        tur.fd(50)
        tur.right(90)
        tur.fd(50)
        tur.right(90)
        tur.fd(50)
        tur.right(90)
        tur.fd(50)
    elif letter == "P":
        tur.setheading(0)
        tur.pd()
        tur.fd(25)
        tur.right(90)
        tur.fd(25)
        tur.right(90)
        tur.fd(25)
        tur.right(90)
        tur.fd(25)
        tur.left(180)
        tur.fd(50)
        tur.left(180)
        tur.fd(50)
        tur.right(90)
        tur.fd(25)      
    elif letter == "Q":
        tur.right(90)
        tur.fd(60)
        tur.left(90)
        tur.fd(30)
        tur.right(45)
        tur.fd(30)
        tur.right(180)
        tur.fd(60)
        tur.left(180)
        tur.fd(30)
        tur.left(140)
        tur.fd(60)
        tur.left(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
    elif letter == "R":
        tur.pd()
        tur.right(90)
        tur.fd(60)
        tur.left(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(45)
        tur.fd(50)
        tur.left(180)
        tur.fd(50)
        tur.right(45)
        tur.fd(30)
        tur.right(90)
        tur.fd(30)
    elif letter == "S":
        tur.pu()
        tur.right(90)
        tur.fd(60)
        tur.pd()
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(30)
    elif letter == "T":
        tur.fd(30)
        tur.right(90)
        tur.fd(60)
        tur.right(180)
        tur.fd(60)
        tur.right(90)
        tur.fd(30)
    elif letter == "U":
        tur.right(90)
        tur.fd(60)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(60)
        tur.right(90)
    elif letter == "V":
        tur.right(45)
        tur.fd(100)
        tur.left(90)
        tur.fd(100)
        tur.right(45)
    
    elif letter == "W":
        tur.right(45)
        tur.fd(100)
        tur.left(90)
        tur.fd(50)
        tur.right(90)
        tur.fd(50)
        tur.left(90)
        tur.fd(100)
        tur.right(45)
        
        
    elif letter == "X":
        tur.right(45)
        tur.fd(150)
        tur.right(135)
        tur.penup()
        tur.fd(75)
        tur.right(135)
        tur.fd(150)
        tur.right(45)
        
        
    elif letter == "Y":
        tur.right(45)
        tur.fd(50)
        tur.right(45)
        tur.fd(100)
        tur.right(180)
        tur.fd(100)
        tur.right(45)
        tur.fd(50)
        tur.right(45)
        
    elif letter == "Z":
        tur.fd(100)
        tur.right(135)
        tur.fd(150)
        tur.left(135)
        tur.fd(100)
        
    elif letter == "Ax":
        # code here
        tur.forward(40)
        
    else:
        #handles space, punctuation, and anything else
        tur.forward(40)
    
if __name__ == "__main__":
    window = turtle.Screen()
    tur = turtle.Turtle()
    tur.speed(1)
    #turtleLetter("box",tur)
    turtleLetter("A",tur)


    window.exitonclick()
